"""empty message

Revision ID: 11dc283379a
Revises: 241767de5da
Create Date: 2016-02-17 20:37:24.812202

"""

# revision identifiers, used by Alembic.
revision = '11dc283379a'
down_revision = '241767de5da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_songs', sa.Column('rank', sa.Integer(), nullable=False))
    op.alter_column('top_songs', 'streams',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('top_songs', 'streams',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('top_songs', 'rank')
    ### end Alembic commands ###
