"""empty message

Revision ID: 1776c86d574
Revises: 42ff6027d3a
Create Date: 2016-02-16 08:59:20.673661

"""

# revision identifiers, used by Alembic.
revision = '1776c86d574'
down_revision = '42ff6027d3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('value', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'value')
    ### end Alembic commands ###
