"""empty message

Revision ID: 1b134bc80cc
Revises: 5388792ecbc
Create Date: 2015-12-14 08:13:20.287304

"""

# revision identifiers, used by Alembic.
revision = '1b134bc80cc'
down_revision = '5388792ecbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
