"""empty message

Revision ID: 241767de5da
Revises: 3dbac9d574d
Create Date: 2016-02-17 20:25:37.430371

"""

# revision identifiers, used by Alembic.
revision = '241767de5da'
down_revision = '3dbac9d574d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('url', sa.String(length=255), nullable=True))
    op.add_column('top_songs', sa.Column('streams', sa.Integer(), nullable=False))
    op.drop_column('top_songs', 'rank')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_songs', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('top_songs', 'streams')
    op.drop_column('songs', 'url')
    ### end Alembic commands ###
