"""empty message

Revision ID: 243741ed950
Revises: 1776c86d574
Create Date: 2016-02-16 12:12:03.674283

"""

# revision identifiers, used by Alembic.
revision = '243741ed950'
down_revision = '1776c86d574'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='operator_pkey')
    )
    ### end Alembic commands ###
