"""empty message

Revision ID: 3dbac9d574d
Revises: 243741ed950
Create Date: 2016-02-16 18:22:09.745086

"""

# revision identifiers, used by Alembic.
revision = '3dbac9d574d'
down_revision = '243741ed950'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_country_vectors_country_id'), 'country_vectors', ['country_id'], unique=False)
    op.create_index(op.f('ix_song_vectors_song_id'), 'song_vectors', ['song_id'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_song_vectors_song_id'), table_name='song_vectors')
    op.drop_index(op.f('ix_country_vectors_country_id'), table_name='country_vectors')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    ### end Alembic commands ###
