"""empty message

Revision ID: 5388792ecbc
Revises: None
Create Date: 2015-12-13 12:47:21.696555

"""

# revision identifiers, used by Alembic.
revision = '5388792ecbc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
