countries = {
    'United States': {'id': 1, 'abbrev': 'us'},
    'United Kingdom': {'id': 2, 'abbrev': 'gb'},
    'Andorra': {'id': 3, 'abbrev': 'ad'},
    'Argentina': {'id': 4, 'abbrev': 'ar'},
    'Australia': {'id': 5, 'abbrev': 'au'},
    'Austria': {'id': 6, 'abbrev': 'at'},
    'Belgium': {'id': 7, 'abbrev': 'be'},
    'Bolivia': {'id': 8, 'abbrev': 'bo'},
    'Brazil': {'id': 9, 'abbrev': 'br'},
    'Bulgaria': {'id': 10, 'abbrev': 'bg'},
    'Canada': {'id': 11, 'abbrev': 'ca'},
    'Chile': {'id': 12, 'abbrev': 'cl'},
    'Colombia': {'id': 13, 'abbrev': 'co'},
    'Costa': {'id': 14, 'abbrev': 'cr'},
    'Cyprus': {'id': 15, 'abbrev': 'cy'},
    'Czech': {'id': 16, 'abbrev': 'cz'},
    'Denmark': {'id': 17, 'abbrev': 'dk'},
    'Dominican Republic': {'id': 18, 'abbrev': 'do'},
    'Ecuador': {'id': 19, 'abbrev': 'ec'},
    'El Salvador': {'id': 20, 'abbrev': 'sv'},
    'Estonia': {'id': 21, 'abbrev': 'ee'},
    'Finland': {'id': 22, 'abbrev': 'fi'},
    'France': {'id': 23, 'abbrev': 'fr'},
    'Germany': {'id': 24, 'abbrev': 'de'},
    'Greece': {'id': 25, 'abbrev': 'gr'},
    'Guatemala': {'id': 26, 'abbrev': 'gt'},
    'Honduras': {'id': 27, 'abbrev': 'hn'},
    'Hong Kong': {'id': 28, 'abbrev': 'hk'},
    'Hungary': {'id': 29, 'abbrev': 'hu'},
    'Iceland': {'id': 30, 'abbrev': 'is'},
    'Ireland': {'id': 31, 'abbrev': 'ie'},
    'Italy': {'id': 32, 'abbrev': 'it'},
    'Latvia': {'id': 33, 'abbrev': 'lv'},
    'Lithuania': {'id': 34, 'abbrev': 'lt'},
    'Luxembourg': {'id': 35, 'abbrev': 'lu'},
    'Malaysia': {'id': 36, 'abbrev': 'my'},
    'Malta': {'id': 37, 'abbrev': 'mt'},
    'Mexico': {'id': 38, 'abbrev': 'mx'},
    'Netherlands': {'id': 39, 'abbrev': 'nl'},
    'New Zealand': {'id': 40, 'abbrev': 'nz'},
    'Nicaragua': {'id': 41, 'abbrev': 'ni'},
    'Norway': {'id': 42, 'abbrev': 'no'},
    'Panama': {'id': 43, 'abbrev': 'pa'},
    'Paraguay': {'id': 44, 'abbrev': 'py'},
    'Peru': {'id': 45, 'abbrev': 'pe'},
    'Philippines': {'id': 46, 'abbrev': 'ph'},
    'Poland': {'id': 47, 'abbrev': 'pl'},
    'Portugal': {'id': 48, 'abbrev': 'pt'},
    'Singapore': {'id': 49, 'abbrev': 'sg'},
    'Slovakia': {'id': 50, 'abbrev': 'sk'},
    'Spain': {'id': 51, 'abbrev': 'es'},
    'Sweden': {'id': 52, 'abbrev': 'se'},
    'Switzerland': {'id': 53, 'abbrev': 'ch'},
    'Taiwan': {'id': 54, 'abbrev': 'tw'},
    'Turkey': {'id': 55, 'abbrev': 'tr'},
    'Uruguay': {'id': 56, 'abbrev': 'uy'}
}
